---
title: "Question 4"
author: "AO XU; Kabir Snell"
date: "2022-10-31"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r} 
library(tidyverse)
library(tidymodels)
library(modelr)
library(rsample)
library(yardstick)

# read data
url <- 'https://raw.githubusercontent.com/pstat197/pstat197a/main/materials/labs/lab4-logistic/data/biomarker_clean.csv'

s_star <- c("DERM", "RELT", "IgD", "PTN", "FSTL1")
biomarker <- read_csv(url) %>%
  # subset to proteins of interest and group
  select(group, any_of(s_star)) %>%
  # convert group (chr) to binary (lgl)
  mutate(class = (group == 'ASD')) %>%
  select(-group)
```

```{r}
# for reproducibility
set.seed(102022)

# partition data
partitions <- biomarker %>%
  initial_split(prop = 0.8)

# examine
partitions
```
```{r}
# training set
training(partitions) %>% head(4)
```
```{r}
# testing set
testing(partitions) %>% head(4)
```
Fitting a logistic regression model:
```{r}
# fit glm
fit <- glm(class ~ ., 
           data = biomarker, 
           family = binomial(link = "logit"))
```
```{r}
tidy(fit)
```
Accuracy measures
```{r}
# tabulate
testing(partitions) %>%
  add_predictions(fit, type = 'response') %>%
  mutate(pred.class = (pred > 0.5)) %>%
  select(class, pred.class) %>%
  table()
```
```{r}
# store predictions as factors
pred_df <- testing(partitions) %>%
  add_predictions(fit, type = 'response') %>%
  mutate(pred.class = (pred > 0.5),
         group = factor(class, labels = c('TD', 'ASD')),
         pred.group = factor(pred.class, labels = c('TD', 'ASD'))) 

# check order of factor levels
pred_df %>% pull(group) %>% levels()
```

```{r}
# compute specificity
pred_df %>%
  specificity(truth = group, 
              estimate = pred.group,
              event_level = 'second')
# accuracy
pred_df %>%
  accuracy(truth = group,
              estimate = pred.group,
              event_level = 'second')
# sensitivity
pred_df %>%
  sensitivity(truth = group,
              estimate = pred.group,
              event_level = 'second')
```

```{r}
# define panel (arguments must be yardstick metric function names)
panel_fn <- metric_set(accuracy, sensitivity, specificity)

# compute
pred_df %>%
  panel_fn(truth = group,
           estimate = pred.group,
           event_level = 'second')
```

Fitting a Gaussian model:
```{r}
# fit glm
fit1 <- glm(class ~ ., 
           data = biomarker, 
           family = gaussian(link = "identity"))
```

```{r}
tidy(fit1)
```

Accuracy measures
```{r}
# tabulate
testing(partitions) %>%
  add_predictions(fit1, type = 'response') %>%
  mutate(pred.class = (pred > 0.5)) %>%
  select(class, pred.class) %>%
  table()
```
```{r}
# store predictions as factors
pred_df <- testing(partitions) %>%
  add_predictions(fit1, type = 'response') %>%
  mutate(pred.class = (pred > 0.5),
         group = factor(class, labels = c('TD', 'ASD')),
         pred.group = factor(pred.class, labels = c('TD', 'ASD'))) 

# check order of factor levels
pred_df %>% pull(group) %>% levels()
```
```{r}
# compute specificity
pred_df %>%
  specificity(truth = group, 
              estimate = pred.group,
              event_level = 'second')
# accuracy
pred_df %>%
  accuracy(truth = group,
              estimate = pred.group,
              event_level = 'second')
# sensitivity
pred_df %>%
  sensitivity(truth = group,
              estimate = pred.group,
              event_level = 'second')
```
Fitting a Quasi model:
```{r}
# fit glm
fit2 <- glm(class ~ ., 
           data = biomarker, 
           family = quasi(link = "identity", variance = "constant"))
```

```{r}
tidy(fit2)
```
Accuracy measures
```{r}
# tabulate
testing(partitions) %>%
  add_predictions(fit2, type = 'response') %>%
  mutate(pred.class = (pred > 0.5)) %>%
  select(class, pred.class) %>%
  table()
```
```{r}
# store predictions as factors
pred_df <- testing(partitions) %>%
  add_predictions(fit2, type = 'response') %>%
  mutate(pred.class = (pred > 0.5),
         group = factor(class, labels = c('TD', 'ASD')),
         pred.group = factor(pred.class, labels = c('TD', 'ASD'))) 

# check order of factor levels
pred_df %>% pull(group) %>% levels()
```
```{r}
# compute specificity
pred_df %>%
  specificity(truth = group, 
              estimate = pred.group,
              event_level = 'second')
# accuracy
pred_df %>%
  accuracy(truth = group,
              estimate = pred.group,
              event_level = 'second')
# sensitivity
pred_df %>%
  sensitivity(truth = group,
              estimate = pred.group,
              event_level = 'second')
```
The accuracy for using Gaussian model is 0.6774194 while that of using logistic regression model is 0.7096774.
In a short, we find a simpler and similar way that using Gaussian model to achieve comparable classification accuracy.




